# Generated by Django 2.2.1 on 2019-05-11 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='texto')),
                ('activa', models.BooleanField(default=False, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeral', models.CharField(max_length=2, verbose_name='numeral')),
                ('texto', models.CharField(max_length=50, verbose_name='texto')),
                ('votos', models.IntegerField(default=0, verbose_name='votos')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Pregunta')),
            ],
            options={
                'verbose_name': 'Opcion',
                'verbose_name_plural': 'Opciones',
            },
        ),
    ]
