# Generated by Django 2.2.1 on 2019-05-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=300, verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
    ]
