# Generated by Django 2.2.1 on 2019-06-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20190515_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('semestre', models.CharField(choices=[('I Semestre', 'I Semestre'), ('II Semestre', 'II Semestre'), ('III Semestre', 'III Semestre'), ('IV Semestre', 'IV Semestre'), ('V Semestre', 'V Semestre')], default='I Semestre', max_length=15)),
                ('programacion', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='numeral',
        ),
        migrations.AddField(
            model_name='opcion',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2')], default=1, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='PreguntaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Estudiante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Pregunta')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='pregunta',
            field=models.ManyToManyField(through='aplicacion.PreguntaEstudiante', to='aplicacion.Pregunta'),
        ),
    ]
