# Generated by Django 2.2.1 on 2019-06-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20190625_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='programacion',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=3),
        ),
    ]
