# Generated by Django 2.2.1 on 2019-06-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20190625_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.TipoPregunta'),
            preserve_default=False,
        ),
    ]
