insert  into `aplicacion_pregunta`(`id`,`texto`,`activa`) values 
	(1,'1. Entiendo mejor algo',1),
	(2,'2. Me considero',1),
	(3,'3. Cuando pienso acerca de lo que hice ayer, es más probable que lo haga sobre la base de',1),
	(4,'4. Tengo tendencia a',1),
	(5,'5. Cuando estoy aprendiendo algo nuevo, me ayuda',0),
	(6,'6. Si yo fuera profesor, yo preferiría dar un curso',0),
	(7,'7. Prefiero obtener información nueva de',0),
	(8,'8. Una vez que entiendo',0),
	(9,'9. En un grupo de estudio que trabaja con un material difícil, es más probable que',0),
	(10,'10. Es más fácil para mí',0),
	(11,'11. En un libro con muchas imágenes y gráficas es más probable que',0),
	(12,'12. Cuando resuelvo problemas de matemáticas',0),
	(13,'13. En las clases a las que he asistido',0),
	(14,'14. Cuando leo temas que no son de ficción, prefiero',0),
	(15,'15. Me gustan los maestros',0),
	(16,'16. Cuando estoy analizando un cuento o una novela',0),
	(17,'17. Cuando comienzo a resolver un problema de tarea, es más probable que',0),
	(18,'18. Prefiero la idea de',0),
	(19,'19. Recuerdo mejor',0),
	(20,'20. Es más importante para mí que un profesor',0),
	(21,'21. Prefiero estudiar',0),
	(22,'22. Me considero',0),
	(23,'23. Cuando alguien me da direcciones de nuevos lugares, prefiero',0),
	(24,'24. Aprendo',0),
	(25,'25. Prefiero primero',0),
	(26,'26. Cuando leo por diversión, me gustan los escritores que',0),
	(27,'27. Cuando veo un esquema o bosquejo en clase, es más probable que recuerde',0),
	(28,'28. Cuando me enfrento a un cuerpo de información',0),
	(29,'29. Recuerdo más fácilmente',0),
	(30,'30. Cuando tengo que hacer un trabajo, prefiero',0),
	(31,'31. Cuando alguien me enseña datos, prefiero',0),
	(32,'32. Cuando escribo un trabajo, es más probable que',0),
	(33,'33. Cuando tengo que trabajar en un proyecto de grupo, primero quiero',0),
	(34,'34. Considero que es mejor elogio llamar a alguien',0),
	(35,'35. Cuando conozco gente en una fiesta, es más probable que recuerde',0),
	(36,'36. Cuando estoy aprendiendo un tema, prefiero',0),
	(37,'37. Me considero',0),
	(38,'38. Prefiero cursos que dan más importancia a',0),
	(39,'39. Para divertirme, prefiero',0),
	(40,'40. Algunos profesores inician sus clases haciendo un bosquejo de lo que enseñarán. Esos bosquejos son',0),
	(41,'41. La idea de hacer una tarea en grupo con una sola calificación para todos',0),
	(42,'42. Cuando hago grandes cálculos',0),
	(43,'43. Tiendo a recordar lugares en los que he estado',0),
	(44,'44. Cuando resuelvo problemas en grupo, es más probable que yo',0);

